# This is a template yaml for the aptos-indexer-processor.
health_check_port: 8085
server_config:
  processor_config:
    type: "events_processor"
  transaction_stream_config:
    indexer_grpc_data_service_address: "https://grpc.testnet.aptoslabs.com:443"
    # At which tx version to start indexing, usually this is the tx version when the contract was deployed
    starting_version: 5936597868
    # At which tx version to stop indexing
    # request_ending_version: 10000
    # Go to https://developers.aptoslabs.com/ to create a project and get an API token
    auth_token: "auth_token_you_can_get_from_aptos_build"
    request_name_header: "events-processor"
  db_config:
    # do not include the ?sslmode=require in the connection string when using cloud DB, it will cause an error
    postgres_connection_string: "postgresql://username:password@neon_host/db_name"
    # we set db_pool_size to a lower number on cloud because we use a free plan
    db_pool_size: 25
  contract_config:
    contract_address: "your_contract_address"
