health_check_port: 8085
server_config:
  processor_config:
    type: "marketplace_indexer"
  transaction_stream_config:
    indexer_grpc_data_service_address: "https://grpc.mainnet.aptoslabs.com:443"
    # rarible starting version: 1011760686
    # wapal starting version:    216804176
    # tradeport starting version: 94194505
    starting_version: 1
    # request_ending_version: 10000
    auth_token: ""
    request_name_header: ""
  db_config:
    # do not include the sslmode=require in the connection string, Use the native TLS implementation in rust
    # don't know why it's not working with the sslmode=require
    postgres_connection_string: "_"
    # we set db_pool_size to a lower number on cloud because we use a free plan
    # see limitation on vercel docs https://vercel.com/docs/storage/vercel-postgres/faq
    db_pool_size: 25
  custom_config:
    marketplace_indexer: [
        # wapal
        "0x584b50b999c78ade62f8359c91b5165ff390338d45f8e55969a04e65d76258c9",
        # tradeport
        "0xe11c12ec495f3989c35e1c6a0af414451223305b579291fc8f3d9d0575a23c26",
        # rarible
        "0x465a0051e8535859d4794f0af24dbf35c5349bedadab26404b20b825035ee790",
      ]
